# Generated by Django 5.2.7 on 2025-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="upload/data/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(editable=False, max_length=255)),
                (
                    "process_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("process_absorbance", "absorbance"),
                            ("process_ph", "ph"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
