# Generated by Django 5.2.7 on 2025-10-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsorbanceProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wave_start", models.FloatField(default=400.0)),
                ("wave_end", models.FloatField(default=750.0)),
            ],
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="process_method",
            field=models.CharField(
                blank=True,
                choices=[("process_absorbance", "absorbance")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AbsorbanceLocalMaximum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wave_start", models.FloatField()),
                ("wave_end", models.FloatField()),
                (
                    "absorbance_properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.absorbanceproperties",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsorbanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wave_nm", models.FloatField()),
                ("absorbance_au", models.FloatField()),
                ("dark_counts", models.FloatField()),
                ("ref_counts", models.FloatField()),
                ("sample_counts", models.FloatField()),
                (
                    "absorbance_properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.absorbanceproperties",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.uploadedfile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="absorbanceproperties",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data.sample"
            ),
        ),
    ]
