# Generated by Django 5.2.7 on 2025-10-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_absorbanceproperties_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="date",
        ),
    ]
